CREATE TABLE Categories (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	parent_id INT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (parent_id) REFERENCES Categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;