INSERT INTO categories (name) VALUES
('Trang phục nam'),
('Trang phục nữ'),
('Áo nam'),
('Quần nam'),
('Áo nữ'),
('Quần nữ'),
('Chân váy'),
('Đầm nữ'),
('Áo thun nam'),
('Áo sơ mi nam'),
('Áo hoodie nam'),
('Áo len nam'),
('Áo khoác nam'),
('Quần jogger nam'),
('Quần jean nam'),
('Quần kaki nam'),
('Quần shorts nam'),
('Quần tây nam'),
('Áo thun nữ'),
('Áo sơ mi nữ'),
('Áo khoác nữ'),
('Quần jean nữ'),
('Quần kaki nữ'),
('Quần legging nữ'),
('Quần shorts nữ'),
('Quần tây nữ'),
('Đầm suông nữ'),
('Đầm xòe nữ'),
('Đầm ôm nữ');